# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 434)
        MainWindow.setMinimumSize(QtCore.QSize(250, 175))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.label_name.setObjectName("label_name")
        self.input_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(110, 10, 113, 21))
        self.input_name.setObjectName("input_name")
        self.label_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_num.setObjectName("label_num")
        self.input_num = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_num.setGeometry(QtCore.QRect(110, 50, 113, 21))
        self.input_num.setObjectName("input_num")
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(20, 90, 191, 28))
        self.button_submit.setObjectName("button_submit")
        self.score_1_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_1_label.setGeometry(QtCore.QRect(10, 150, 51, 20))
        self.score_1_label.setObjectName("score_1_label")
        self.score_1_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score_1_input.setGeometry(QtCore.QRect(110, 150, 113, 22))
        self.score_1_input.setObjectName("score_1_input")
        self.score_2_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_2_label.setGeometry(QtCore.QRect(10, 190, 55, 16))
        self.score_2_label.setObjectName("score_2_label")
        self.score_2_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score_2_input.setGeometry(QtCore.QRect(110, 190, 113, 22))
        self.score_2_input.setObjectName("score_2_input")
        self.score_3_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_3_label.setGeometry(QtCore.QRect(10, 230, 55, 16))
        self.score_3_label.setObjectName("score_3_label")
        self.score_3_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score_3_input.setGeometry(QtCore.QRect(110, 230, 113, 22))
        self.score_3_input.setObjectName("score_3_input")
        self.score_4_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_4_label.setGeometry(QtCore.QRect(10, 270, 55, 16))
        self.score_4_label.setObjectName("score_4_label")
        self.score_4_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score_4_input.setGeometry(QtCore.QRect(110, 270, 113, 22))
        self.score_4_input.setObjectName("score_4_input")
        self.response_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.response_label.setGeometry(QtCore.QRect(100, 320, 161, 16))
        self.response_label.setStyleSheet("QLabel {\n"
"        color: green; /* Text color */\n"
"    }")
        self.response_label.setObjectName("response_label")
        self.button_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_save.setGeometry(QtCore.QRect(80, 350, 191, 28))
        self.button_save.setObjectName("button_save")
        self.response_label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.response_label_name.setGeometry(QtCore.QRect(240, 10, 121, 16))
        self.response_label_name.setStyleSheet("QLabel  {\n"
"        color: red; /* Text color */\n"
"    }")
        self.response_label_name.setObjectName("response_label_name")
        self.response_label_number = QtWidgets.QLabel(parent=self.centralwidget)
        self.response_label_number.setGeometry(QtCore.QRect(240, 50, 131, 16))
        self.response_label_number.setStyleSheet("QLabel  {\n"
"        color: red; /* Text color */\n"
"    }")
        self.response_label_number.setObjectName("response_label_number")
        self.score_response_label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_response_label_1.setGeometry(QtCore.QRect(240, 150, 121, 16))
        self.score_response_label_1.setStyleSheet("QLabel  {\n"
"        color: red; /* Text color */\n"
"    }")
        self.score_response_label_1.setObjectName("score_response_label_1")
        self.score_response_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_response_label_2.setGeometry(QtCore.QRect(240, 190, 121, 16))
        self.score_response_label_2.setStyleSheet("QLabel  {\n"
"        color: red; /* Text color */\n"
"    }")
        self.score_response_label_2.setObjectName("score_response_label_2")
        self.score_response_label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_response_label_3.setGeometry(QtCore.QRect(240, 230, 121, 16))
        self.score_response_label_3.setStyleSheet("QLabel  {\n"
"        color: red; /* Text color */\n"
"    }")
        self.score_response_label_3.setObjectName("score_response_label_3")
        self.score_response_label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.score_response_label_4.setGeometry(QtCore.QRect(240, 270, 121, 16))
        self.score_response_label_4.setStyleSheet("QLabel  {\n"
"        color: red; /* Text color */\n"
"    }")
        self.score_response_label_4.setObjectName("score_response_label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grades"))
        self.label_name.setText(_translate("MainWindow", "Student name:"))
        self.label_num.setText(_translate("MainWindow", "No of attempts:"))
        self.button_submit.setText(_translate("MainWindow", "Submit"))
        self.score_1_label.setText(_translate("MainWindow", "Score 1:"))
        self.score_2_label.setText(_translate("MainWindow", "Score 2:"))
        self.score_3_label.setText(_translate("MainWindow", "Score 3:"))
        self.score_4_label.setText(_translate("MainWindow", "Score 4:"))
        self.response_label.setText(_translate("MainWindow", "Data was sucessfully saved"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.response_label_name.setText(_translate("MainWindow", "Please give a name."))
        self.response_label_number.setText(_translate("MainWindow", "Enter 1 to 4"))
        self.score_response_label_1.setText(_translate("MainWindow", "Enter 0 to 100"))
        self.score_response_label_2.setText(_translate("MainWindow", "Enter 0 to 100"))
        self.score_response_label_3.setText(_translate("MainWindow", "Enter 0 to 100"))
        self.score_response_label_4.setText(_translate("MainWindow", "Enter 0 to 100"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
